name: builds

on:
  release:
    types: [published, created, edited]

jobs:
  check:
    name: Build Programs
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Build Wiimm's Iso Tools
      run: nix build .#wiimms-iso-tools
    - name: Build Slippi Netplay
      run: nix build .#slippi-netplay
    - name: Build Slippi Playback
      run: nix build .#slippi-playback
    - name: Build Gecko Tools
      run: nix build .#gecko
    - name: Build PowerPC-EABI-Assembling
      run: nix build .#powerpc-eabi-assembling
    - name: Build GCMTool
      run: nix build .#gcmtool
